### ISSUE TITLE
Enabling Inspector2 leads to Internal Server Error

### ISSUE THREAD

**Issue by goedelsoup** [alexjurkiewicz/ecr-scan-image#19]
We had been rolling out use of this action in a redesign of our pipelines, where it had been working fine for several weeks. After enabling Inspector v2 this past week, the next run of the pipeline complained about missing permissions:

```
User: arn:aws:sts::***:assumed-role/${role_name}/${instance_id} is not authorized to perform: inspector2:ListFindings on resource: arn:aws:inspector2:${region}:***:/findings/list
```

After granting the above action, I began receiving only `Error: An internal server error has occured` with no additional logs. I assumed an unhandled error for a missing `inspector2:GetFindingsReportStatus` was being swallowed, but even after granting that action to `*`, I still only received the server error message. None of the existing ECR permissions were modified, so it seems like AWS may have unintentionally broken API compatibility.

**Comment by goedelsoup** [comment]
Logging into the relevant GitHub action runner, it appears the same response is received when using the CLI:
```
$ AWS_DEFAULT_REGION=us-east-1 aws ecr describe-image-scan-findings --repository-name ${repo_name} --image-id imageTag=${image_tag}

An error occurred (ServerException) when calling the DescribeImageScanFindings operation (reached max retries: 4): An internal server error has occured
```

The issue appears lie with AWS or a configuration gotcha when using Inspector that I am still overlooking. Will continue to note any findings here and submit a PR with a README update that can help others in the future.

**Comment by alexjurkiewicz** [comment]
Do you use AWS Org and have some SCPs deployed?
You can try to check CloudTrail for the IAM user, you should see a more complete error message there. I'll close this issue for now, but please update again if you find the solution.
