### ISSUE TITLE
Deprecation warning due to set-output

### ISSUE THREAD

**Issue by prachisr** [alexjurkiewicz/ecr-scan-image#27]
Github Actions is deprecating the use of set-output and save-state. More details https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. On running the action we currently get the following warning: `The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files.`

The actions version needs to be upgraded to v1.10.0 or higher to fix

**Comment by s-a-tanjim** [comment]
I don't think the issue is solved yet. Still getting the same warning.
`Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
`

**Comment by pzi** [comment]
> I don't think the issue is solved yet. Still getting the same warning.
> 
> ```
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
> ```

@s-a-tanjim happy for you to pick it up and propose code changes :)

**Comment by s-a-tanjim** [comment]
@pzi Ohhh my bad. Thanks for the comment. I was following the Readme.md file and got the warning. I created the [pull request](https://github.com/alexjurkiewicz/ecr-scan-image/pull/30) to update the readme file. Thanks.
