### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by david-smith-cko** [alexjurkiewicz/ecr-scan-image#29]
Thanks for your work on this Github Action, Alex.

I'd like to fork your repo, but to do so legally, I believe an appropriate license needs to be in place on this repo.

Would you be willing to add a LICENSE for this repo so that I can do that? Preferably an MIT

**Comment by alexjurkiewicz** [comment]
Sure, can you submit a pull request?

**Comment by pzi** [comment]
Fixed in https://github.com/alexjurkiewicz/ecr-scan-image/pull/33
